### PR TITLE
use AspectList.remove instead of AspectList.reduce to fix "sometimes drainer doesn't work with essentia import bus"

### LINKED ISSUE #20653: Make the apimancer's drainer work with essentia import busses After change essentia-type of drainer
### Your GTNH Discord Username

_No response_

### Your Pack Version

2.7.3

### Your Server

Private Server

### Java Version

Java 17

### Type of Server

Vanilla Forge

### Your Expectation

Place **apimancer's drainer** under the Industial Apiary then Place essentia import bus beside it;
put the bee in the Apiary;
①right click **drainer** with a Phial of Essentia(Messis x 8);
②after some time, right click with Phial of Essentia(Victus x 8);
③after some time, right click with Phial of Essentia(Lucrum x 8);
④after some time, right click with Phial of Essentia(Messis x 8);

essentia import busses should output Messis+Victus+Lucrum to AE.

### The Reality

①it work.
②it didn't work. Victus x 40 is still in drainer after 60seconds.
③it didn't work. Victus x 40+Lucrum x 8 is still in drainer after 60seconds.
④it work? after Messis x 8 was put in the drainer by bee, Messis x 8+Victus x 40 disappear then go into AE, but Lucrum x 8 is still in drainer after 60seconds.

### Your Proposal

fix this bug
PS. I have seen #16027 but this bug is different.

### Final Checklist

- [x] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [x] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

### PR DESCRIPTION
**Pull request by SST-03**
use AspectList.remove(...) instead of .reduce(...) can remove Aspect when aspect.amount==0.
closes GTNewHorizons/GT-New-Horizons-Modpack#20653

### CODE REVIEW

**Comment by SST-03** [comment]
wait how does build and test fail
why?????

**Comment by SST-03** [comment]
> Some mod use postea or postea is set in dev in this mod. To resolve it run gradlew updatebuildscript or found the mod run it there add a new tag and update this mod .

I used .\gradlew updatebuildscript and upload changes to github, but still, it just not works. Do I need to do other things?

**Comment by Dream-Master** [comment]
The mod cause it is now updated and all fine

File: src/main/java/magicbees/tileentity/TileEntityApimancersDrainerCommon.java
Comment (Nikolay-Sitnikov) [inline src/main/java/magicbees/tileentity/TileEntityApimancersDrainerCommon.java:288]: If you absolutely want to fix this, you could add a loop to remove all the zero-essentia entries from the NBT or the `AspectList` here.

Comment (SST-03) [reply src/main/java/magicbees/tileentity/TileEntityApimancersDrainerCommon.java:288]: To fix the old save?

File: src/main/java/magicbees/tileentity/TileEntityApimancersDrainerCommon.java [hunk 1]
```diff
@@ -224,12 +224,10 @@ public int takeEssentia(Aspect aspect, int amount, ForgeDirection face) {
...
-                int total = this.essentia.getAmount(aspect);
-                this.essentia.reduce(aspect, total);
-                return total;
-            }
-            this.essentia.reduce(aspect, amount);
+
+            int total = this.essentia.getAmount(aspect);
+            this.essentia.remove(aspect, amount); // if amount >= total then it will also remove aspect.
+            if (amount > total) return total;
             return amount;
```
Comment (Nikolay-Sitnikov) [inline src/main/java/magicbees/tileentity/TileEntityApimancersDrainerCommon.java]: Can be simplified to `return Math.min(amount, total);`

**Review by Nikolay-Sitnikov — APPROVED** [review]
LGTM!
